# Generated by Django 5.0.6 on 2024-07-04 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_age_alter_user_email_alter_user_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(error_messages={'blank': '닉네임을 입력하시오', 'unique': '해당 닉네임이 이미 존재합니다.'}, max_length=50, unique=True),
        ),
    ]
