# Generated by Django 5.0.6 on 2024-07-04 08:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_age_alter_user_email_alter_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.PositiveIntegerField(error_messages={'blank': '나이를 설정하시오'}, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(error_messages={'unique': '해당 닉네임이 이미 존재합니다.'}, max_length=50, unique=True, validators=[django.core.validators.RegexValidator(code='invalid', message='닉네임을 입력하시오', regex='^[^\\s]+$')]),
        ),
    ]
