# Generated by Django 5.0.6 on 2024-07-04 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_age_alter_user_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('남자', '남자(Man)'), ('여자', '여자(Woman)')], error_messages={'blank': '성별을 선택하시오'}, max_length=2),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(error_messages={'unique': '해당 닉네임이 이미 존재합니다.'}, max_length=50, unique=True),
        ),
    ]
