# Generated by Django 5.0.6 on 2024-07-05 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0001_initial'),
        ('users', '0016_user_followings'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='acheivement',
            field=models.ManyToManyField(blank=True, related_name='users', to='achievements.achievement'),
        ),
    ]
