# Generated by Django 5.0.6 on 2024-07-06 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_user_acheivement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='acheivement',
        ),
    ]
