# Generated by Django 5.0.6 on 2024-07-05 15:53

import achievements.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('explain', models.CharField(blank=True, max_length=200, null=True)),
                ('badge', models.ImageField(blank=True, null=True, upload_to=achievements.models.achievement_directory_path)),
                ('unlock_status', models.IntegerField(choices=[(1, 'Unlocked'), (2, 'Locked')], default=1)),
            ],
        ),
    ]
