# Generated by Django 5.0.6 on 2024-07-06 07:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0002_alter_achievement_explain_alter_achievement_title_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='users',
            field=models.ManyToManyField(related_name='achievements', to=settings.AUTH_USER_MODEL),
        ),
    ]
