# Generated by Django 5.0.6 on 2024-07-07 07:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0003_achievement_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievement',
            name='explain',
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='unlock_status',
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='users',
        ),
        migrations.AddField(
            model_name='achievement',
            name='default_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='achievement',
            name='expain',
            field=models.CharField(default='업적 달성 조건', max_length=300),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locked', models.BooleanField(default=False)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='achievements.achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'achievement')},
            },
        ),
    ]
