# Generated by Django 5.0.6 on 2024-07-07 07:44

from django.db import migrations, models

def add_initial_achievements(apps, schema_editor):
    Achievement = apps.get_model('achievements', 'Achievement')

    # 기본 업적 추가
    Achievement.objects.create(
        title='주간지 회원',
        expain='회원가입 시 달성',
        badge='null',
        default_locked=False,
    )

    Achievement.objects.create(
        title='첫 팔로워',
        expain='팔로워가 1명일 경우 달성',
        badge='null',
        default_locked=False,
    )

class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0004_remove_achievement_explain_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='expain',
            field=models.CharField(default='업적 달성 조건', max_length=500),
        ),
        migrations.RunPython(add_initial_achievements),
    ]
